name: build

on:
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
      - 'Makefile'
      - '**.mk'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        cases:
          - "iperf_tcp_client"
          - "iperf_udp_server"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: "recursive"

        - name: Install
          run: |
            sudo apt install -y make

        - name: Build 
          working-directory: test
          run: |
            cd ${{ matrix.cases }}
            make CONFIG_CHIP_NAME=BL602 CONFIG_LINK_ROM=1 -j
            mkdir output 
            cp build/${{ matrix.cases }}.bin output/
            cp ../partition_cfg_2MB-20220627.toml output/

        - name: ${{ matrix.cases }}
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.cases }}
            path: test/${{ matrix.cases }}/output
